apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.global.namespace }}
data:
  DATABASE_HOST: {{ .Values.config.DATABASE_HOST | quote }}
  DATABASE_PORT: {{ .Values.config.DATABASE_PORT | quote }}
  DATABASE_NAME: {{ .Values.config.DATABASE_NAME | quote }}
  DATABASE_USER: {{ .Values.config.DATABASE_USER | quote }}
  DATABASE_PASSWORD: {{ .Values.config.DATABASE_PASSWORD | quote }}
